'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, Search, Link2, Check, FileDown, LockKeyhole, ArrowDown, X } from 'lucide-react';
import type { ArchiveInfo } from '@/lib/archive';
import type { Message } from '@/lib/parser';
function MessageText({text}:{text:string}) { return <>{text.split(/(https?:\/\/[^\s<>]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} href={part} target="_blank" rel="noreferrer noopener">{part}</a>:<span key={i}>{part}</span>)}</>; }
function Attachment({id,name}:{id:string;name:string}) { const url=`/api/media/${id}?file=${encodeURIComponent(name)}`; const ext=name.split('.').pop()?.toLowerCase()||''; const filename=name.split('/').pop(); return <div className="attachment">{/^(jpg|jpeg|png|webp|gif)$/.test(ext)?<a href={url} target="_blank" rel="noreferrer"><img src={url} alt={filename} loading="lazy"/></a>:/^(mp4|mov)$/.test(ext)?<video controls preload="none" src={url}/>: /^(opus|ogg|mp3|m4a|aac|wav)$/.test(ext)?<audio controls preload="none" src={url}/>:<div className="document-card"><div className="document"><FileDown size={27}/><span>{filename}<small>{ext.toUpperCase()} document</small></span></div><div className="document-actions">{ext==='pdf'&&<a href={`${url}&view=1`} target="_blank" rel="noopener noreferrer" aria-label={`View ${filename}`}>View ↗</a>}<a href={url} download={filename} aria-label={`Download ${filename}`}>Download</a></div></div>}{/^(mp4|mov|opus|ogg|mp3|m4a|aac|wav)$/.test(ext)&&<a className="media-download" href={url} download={filename}>Download original · {ext.toUpperCase()}</a>}</div>; }
export default function Chat({info,messages,participants}:{info:ArchiveInfo;messages:Message[];participants:string[]}) {
 const [query,setQuery]=useState('');const [self,setSelf]=useState(participants.find(p=>p==='Shawn')||participants[1]||participants[0]||'');const [copied,setCopied]=useState(false);const [copyError,setCopyError]=useState(false);const [limit,setLimit]=useState(300);
 const filtered=useMemo(()=>messages.filter(m=>(m.text+' '+m.sender+' '+(m.attachment||'')).toLowerCase().includes(query.toLowerCase())),[messages,query]); const visible=filtered.slice(0,limit);
 return <main className="chat-page"><header className="chat-header"><a href="/" className="back-link" aria-label="Back to workspace"><ArrowLeft size={21}/></a><div className="chat-avatar">{info.name.slice(0,2).toUpperCase()}</div><div className="chat-heading"><h1>{info.name}</h1><p>{participants.join(' · ')} <span> · {messages.length.toLocaleString()} messages</span></p></div><button className="share-chat" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setCopyError(true);}}}>{copied?<Check size={17}/>:<Link2 size={17}/>}<span>{copied?'Link copied':'Share conversation'}</span></button></header><div className="chat-toolbar"><div className="chat-search"><Search size={16}/><input aria-label="Search messages" placeholder="Search this conversation" value={query} onChange={e=>{setQuery(e.target.value);setLimit(300);}}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={15}/></button>}</div><label>View as <select value={self} onChange={e=>setSelf(e.target.value)}>{participants.map(p=><option key={p}>{p}</option>)}</select></label><span className="read-only">READ-ONLY ARCHIVE</span></div><div className="message-scroll" id="message-scroll"><div className="chat-notice"><LockKeyhole size={13}/> Archived conversation. Anyone with the share link can view messages and attachments.</div>{copyError&&<p className="chat-notice">Copy the address from your browser to share this conversation.</p>}{query&&<div className="date-pill">{filtered.length} matching messages</div>}<div className="messages">{visible.map((message,i)=><div key={message.id}>{(i===0||visible[i-1].date!==message.date)&&<div className="date-pill">{message.date}</div>}{!message.sender?<div className="system-message">{message.text}</div>:<div className={`message-row ${message.sender===self?'outgoing':'incoming'}`}><div className="message-bubble"><div className="sender-name">{message.sender}</div>{message.attachment&&<Attachment id={info.id} name={message.attachment}/>}<div className="message-text"><MessageText text={message.text}/></div><div className="message-time">{message.time}</div></div></div>}</div>)}{!filtered.length&&<div className="chat-notice">No messages match your search.</div>}{filtered.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+300)}>Load next {Math.min(300,filtered.length-limit)} messages ({filtered.length-limit} remaining)</button>}<div id="chat-end"/></div></div><footer className="chat-bottom"><LockKeyhole size={15}/><span>This is a saved conversation. Messages cannot be sent or edited.</span><button title="Go to last message" aria-label="Go to last message" onClick={()=>{setLimit(filtered.length);setTimeout(()=>document.getElementById('chat-end')?.scrollIntoView({behavior:'smooth'}),50);}}><ArrowDown size={18}/></button></footer></main>;
}
