'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowRight, LockKeyhole, MessageCircle, ShieldCheck, Eye, EyeOff } from 'lucide-react';
import Brand from './brand';
export default function Login() {
  const router = useRouter(); const [error,setError] = useState(''); const [busy,setBusy] = useState(false); const [show,setShow] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(''); const password = new FormData(event.currentTarget).get('password'); try { const response = await fetch('/api/auth', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.refresh(); } catch(error) { setError(error instanceof Error ? error.message : 'Unable to sign in.'); } finally { setBusy(false); } }
  return <main className="login-page"><div className="login-story"><Brand/><div className="story-content"><span className="eyebrow">EVERY CONVERSATION HAS CONTEXT</span><h1>Keep the chat.<br/><em>Keep the story.</em></h1><p>A familiar home for your WhatsApp conversations.<br/>Archive once. Revisit anytime. Share with your team.</p><div className="sample-chat" aria-hidden="true"><div className="sample-top"><MessageCircle size={18}/> A little context goes a long way <span>•••</span></div><div className="sample-bubble">Everything we discussed, in one place.<small>10:24 AM</small></div><div className="sample-bubble green">And ready whenever we need it. <span>✓✓</span><small>10:25 AM</small></div><div className="sample-note"><ShieldCheck size={14}/> Stored on your server. Always in context.</div></div></div><footer>PROPERTYLAB <span>A clearer view of every conversation.</span></footer></div><div className="login-panel"><div className="login-card"><div className="lock-icon"><LockKeyhole size={24}/></div><span className="eyebrow">YOUR PRIVATE WORKSPACE</span><h2>Welcome back.</h2><p>Enter your admin password to open the archive.</p><form onSubmit={submit}><label htmlFor="password">Admin password</label><div className="password-field"><input id="password" name="password" type={show?'text':'password'} required autoComplete="current-password" placeholder="Enter your password"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary login-submit" disabled={busy}>{busy?'Signing in…':'Open workspace'}<ArrowRight size={18}/></button></form><div className="login-hint"><ShieldCheck size={16}/><span>Password required. Your session unlocks the workspace, shared conversations, and attachments.</span></div></div><div className="panel-footer">Made for conversations that matter.</div></div></main>;
}
